train_params:
    n_classes: 2
    n_epoch: 2
    batch_size: 128

image_params:
    size_h: 32
    size_w: 32

optim_params:
    lr: 0.1
    momentum: 0.9

path:
    data_path: data
    save_model_filename: model.pt
    save_model_dirname: model

mlflow_params:
    url: http://127.0.0.1:5000
    name: binary_classification_experiments
